# Generated by Django 3.0.5 on 2020-04-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_patient_social_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
