# Generated by Django 3.0.5 on 2020-04-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='social_no',
        ),
    ]
