# Generated by Django 3.0.5 on 2020-04-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20200403_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_no',
        ),
    ]
